package it.minetti.demo;

import org.junit.jupiter.api.Test;
import org.springframework.boot.test.context.SpringBootTest;

@SpringBootTest
class DemoApplicationTest {

    @Test
    public void contextLoads() {
        // generated by spring initializer
    }
}